Setting up Docker Watch for automatic sync and rebuild for the app and webhook

diff --git a/Dockerfile.webhook b/Dockerfile.webhook
--- a/Dockerfile.webhook
+++ b/Dockerfile.webhook
@@ -20,10 +20,19 @@
 
 FROM node:lts-alpine
 
+#RUN /bin/sh -c set -eux; addgroup -g 2375 -S docker # buildkit
+#ENV DOCKER_VERSION=27.5.0
+#RUN /bin/sh -c set -eux; apkArch="$(apk --print-arch)"; case "$apkArch" in 'x86_64') url='https://download.docker.com/linux/static/stable/x86_64/docker-27.5.0.tgz'; ;; 'armhf') url='https://download.docker.com/linux/static/stable/armel/docker-27.5.0.tgz'; ;; 'armv7') url='https://download.docker.com/linux/static/stable/armhf/docker-27.5.0.tgz'; ;; 'aarch64') url='https://download.docker.com/linux/static/stable/aarch64/docker-27.5.0.tgz'; ;; *) echo >&2 "error: unsupported 'docker.tgz' architecture ($apkArch)"; exit 1 ;; esac; wget -O 'docker.tgz' "$url"; tar --extract --file docker.tgz --strip-components 1 --directory /usr/local/bin/ --no-same-owner 'docker/docker' ; rm docker.tgz; docker --version # buildkit
+#ENV DOCKER_BUILDX_VERSION=0.19.3
+#RUN /bin/sh -c set -eux; apkArch="$(apk --print-arch)"; case "$apkArch" in 'x86_64') url='https://github.com/docker/buildx/releases/download/v0.19.3/buildx-v0.19.3.linux-amd64'; sha256='32ed111e941e385c2fb8261eba06a4056915718fd606f8278834ac1931d261a2'; ;; 'armhf') url='https://github.com/docker/buildx/releases/download/v0.19.3/buildx-v0.19.3.linux-arm-v6'; sha256='744352489292ab1439e4b4facfd49f81cbe25e71e205908bd9ec44618759739c'; ;; 'armv7') url='https://github.com/docker/buildx/releases/download/v0.19.3/buildx-v0.19.3.linux-arm-v7'; sha256='5a83e1663b595147ac0225d876fc77e3b441e62dac7a59523ba7003eb6733b8b'; ;; 'aarch64') url='https://github.com/docker/buildx/releases/download/v0.19.3/buildx-v0.19.3.linux-arm64'; sha256='138b587399b27bb61945a36d67866177b85dea1155101a2be63c7ab715f18a2e'; ;; 'ppc64le') url='https://github.com/docker/buildx/releases/download/v0.19.3/buildx-v0.19.3.linux-ppc64le'; sha256='b9eb337b16a75ad45ff846134d34599169bc6dfdb168fb51303fc6b08ed9f31e'; ;; 'riscv64') url='https://github.com/docker/buildx/releases/download/v0.19.3/buildx-v0.19.3.linux-riscv64'; sha256='de8151fe6ced7118f2d680e1d1e7c5cb00496ca0e8b0f8b261450c6636d86978'; ;; 's390x') url='https://github.com/docker/buildx/releases/download/v0.19.3/buildx-v0.19.3.linux-s390x'; sha256='422a9a0250d52dfdd6b78c8152fbf9df41993be4c7add93438c22122ff6c7da8'; ;; *) echo >&2 "warning: unsupported 'docker-buildx' architecture ($apkArch); skipping"; exit 0 ;; esac; wget -O 'docker-buildx' "$url"; echo "$sha256 *"'docker-buildx' | sha256sum -c -; plugin='/usr/local/libexec/docker/cli-plugins/docker-buildx'; mkdir -p "$(dirname "$plugin")"; mv -vT 'docker-buildx' "$plugin"; chmod +x "$plugin"; docker buildx version # buildkit
+#ENV DOCKER_COMPOSE_VERSION=2.32.3
+#RUN /bin/sh -c set -eux; apkArch="$(apk --print-arch)"; case "$apkArch" in 'x86_64') url='https://github.com/docker/compose/releases/download/v2.32.3/docker-compose-linux-x86_64'; sha256='6ef48e4bf25fbf1f1ad50c43b797cc24e12e4cde29765076b4145e09e35f5713'; ;; 'armhf') url='https://github.com/docker/compose/releases/download/v2.32.3/docker-compose-linux-armv6'; sha256='8f415a76ad62ff621b26b37a94841ee0d4480862d8da55320c1c8fc9db4d8359'; ;; 'armv7') url='https://github.com/docker/compose/releases/download/v2.32.3/docker-compose-linux-armv7'; sha256='64314c73a7d34e4a8b9dad87bab857304fb60b0293703d02be436893e1c37f33'; ;; 'aarch64') url='https://github.com/docker/compose/releases/download/v2.32.3/docker-compose-linux-aarch64'; sha256='d1a04a3eb7fd738cc78e518d179a03adb9fe531ee422b8a14bdccf36d654b73a'; ;; 'ppc64le') url='https://github.com/docker/compose/releases/download/v2.32.3/docker-compose-linux-ppc64le'; sha256='23bddc8119bce6c0eeef1461bc0526291d60de9042b28780012033ba4082090e'; ;; 'riscv64') url='https://github.com/docker/compose/releases/download/v2.32.3/docker-compose-linux-riscv64'; sha256='c4bac574a2123938de4ef410e7cef92d079abe266298c93257cbcc4e17134184'; ;; 's390x') url='https://github.com/docker/compose/releases/download/v2.32.3/docker-compose-linux-s390x'; sha256='6c0c7d9b6119f68b3dcbf816cf9e5782eb7cea8d2433f8a51b95a41276241e18'; ;; *) echo >&2 "warning: unsupported 'docker-compose' architecture ($apkArch); skipping"; exit 0 ;; esac; wget -O 'docker-compose' "$url"; echo "$sha256 *"'docker-compose' | sha256sum -c -; plugin='/usr/local/libexec/docker/cli-plugins/docker-compose'; mkdir -p "$(dirname "$plugin")"; mv -vT 'docker-compose' "$plugin"; chmod +x "$plugin"; ln -sv "$plugin" /usr/local/bin/; docker-compose --version; docker compose version # buildkit
+
+
 WORKDIR /app
 
 # Install make and git
-RUN apk add --no-cache git && mkdir project_root;
+RUN apk add --no-cache curl git && mkdir project_root;
 
 COPY webhook/package*.json ./
 RUN npm install
